using UnityEngine;
using System.Collections;

public class PinchZoom : MonoBehaviour {

    public float perspectiveZoomSpeed = 0.5f;        // The rate of change of the field of view in perspective mode.
    public float orthoZoomSpeed = 0.5f;        // The rate of change of the orthographic size in orthographic mode.
    private Camera cam;

    private float MAX_ZOOM;
    private float MIN_ZOOM;

	// Use this for initialization
	void Start () {
        cam = Camera.main;

        if (cam.orthographic)
        {
            MAX_ZOOM = 3.0f;
            MIN_ZOOM = 5.452521f;
        }

        else
        {
            MAX_ZOOM = 90.0f;
            MIN_ZOOM = 60.0f;
        }
	}


    void Update()
    {
        // If there are two touches on the device...
        if (Input.touchCount == 2)
        {
            // Store both touches.
            Touch touchZero = Input.GetTouch(0);
            Touch touchOne = Input.GetTouch(1);

            // Find the position in the previous frame of each touch.
            Vector2 touchZeroPrevPos = touchZero.position - touchZero.deltaPosition;
            Vector2 touchOnePrevPos = touchOne.position - touchOne.deltaPosition;

            // Find the magnitude of the vector (the distance) between the touches in each frame.
            float prevTouchDeltaMag = (touchZeroPrevPos - touchOnePrevPos).magnitude;
            float touchDeltaMag = (touchZero.position - touchOne.position).magnitude;

            // Find the difference in the distances between each frame.
            float deltaMagnitudeDiff = prevTouchDeltaMag - touchDeltaMag;

            // If the camera is orthographic...
            if (cam.orthographic)
            {
                // ... change the orthographic size based on the change in distance between the touches.
                cam.orthographicSize += deltaMagnitudeDiff * orthoZoomSpeed;

                // Make sure the orthographic size never drops below zero.
                cam.orthographicSize = Mathf.Max(GetComponent<Camera>().orthographicSize, MAX_ZOOM);
                cam.orthographicSize = Mathf.Min(cam.orthographicSize, MIN_ZOOM);
            }
            else
            {
                // Otherwise change the field of view based on the change in distance between the touches.
                cam.fieldOfView += deltaMagnitudeDiff * perspectiveZoomSpeed;

                // Clamp the field of view to make sure it's between 0 and 180.
                GetComponent<Camera>().fieldOfView = Mathf.Clamp(GetComponent<Camera>().fieldOfView, MIN_ZOOM, MAX_ZOOM);
            }
        }
    }
}
