using UnityEngine;
using System.Collections;

public class Swipe : MonoBehaviour {

    public GameObject Restaurant, Grime;
    public Camera MainCamera;
    float RestaurantX, RestaurantY,GrimeX,GrimeY;
    

	// Use this for initialization
	void Start () {
        
    }
	
	// Update is called once per frame
	void Update () {

        if (SwipeManager.Instance.IsSwiping(SwipeDirection.Left))
        {
            
            Debug.Log("Left");
        }
        else if (SwipeManager.Instance.IsSwiping(SwipeDirection.Right))
        {
            Debug.Log("Right");
        }
        else if (SwipeManager.Instance.IsSwiping(SwipeDirection.Up))
        {
            Debug.Log("Up");
        }
        else if (SwipeManager.Instance.IsSwiping(SwipeDirection.Down))
        {
            Debug.Log("Down");
        }

    }
}
